version: '3'

volumes:
  tutorial-db:

services:

  wordpress:
    image: wordpress:latest
    ports:
      - "8084:80"
    volumes:
      - ./src:/var/www/html/


  db:
    image: mariadb:latest
    ports:
      - 3306:3306
    volumes:
      - tutorial-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_USER: "ROOT"
      MYSQL_PASSWORD: "123456"
      MYSQL_DATABASE: "tutorial"

  
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports:
        - 8080:80
